apiVersion: v2
name: data-gateway
description: A GraphQL router deployment forming the Diamond Data Gateway
type: application

version: 0.3.0

dependencies:
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 25.17.0
    condition: prometheus.enabled
  - name: jaeger
    repository: https://jaegertracing.github.io/helm-charts
    version: 2.0.0
    condition: jaeger.enabled
  - name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.83.0
    condition: opentelemetry-collector.enabled
  - name: router
    repository: oci://ghcr.io/apollographql/helm-charts
    version: 1.41.1
    condition: apollo-router.enabled
