version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - .github/workflows
      - workflows/compose
    schedule:
      interval: weekly
    open-pull-requests-limit: 100
    groups:
      github-artifacts:
        patterns:
          - actions/*-artifacts
      minor:
        update-types:
          - minor
          - patch
