site_name: Workflows
site_url: https://diamondlightsource.github.io/graph-federation
repo_url: https://github.com/DiamondLightSource/graph-federation
edit_uri: edit/main/docs/
plugins:
  - techdocs-diamond

nav:
  - Home: index
  - How-To Guides:
      - ... | flat | how-tos/*.md
  - Explanations:
      - ... | flat | explanations/*.md
  - References:
      - ... | flat | references/*.md
