apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: router-apikey
  namespace: data-gateway
spec:
  encryptedData:
    managedFederationApiKey: AgAFF9OYxROjOaslDdnA+TUs+EWiXbAmAoqj3fZrqqqfFHu64LJIHs8UtF2WDfmh9GpU0kNaPo86xDO8hPPIyIEtlcvkmMIdzgt9AUhN9JsqpLqDXJZau9Oe91Y1R63sOIIZH2c3rFYzUhbmWeM32AYtWuxlLTZvjYI08l3Y5rY6vBcFhgO2mnLuHW0ajKPh/DTz3tEr7my3wQmG9cjrLzqITSWot04rMOjfj9Ky4t6RAxvReZx6u1oBlstHNfjzr2dWTsTyvBQhi1+hx7UlkqDwON1YbPkcXiqsRXpAzTrp7a0HyZbSlxrfsrguygzzCm3algIG1iu8OSc/M0YUEvZA37kc4USMh/LaUOSUgn5RbLtUdRpwMbTAc/hIQJpxW0aGYXKjEgZ0MSYYLWyAfyt/rcWaB0kjDWzJwAYNzsW1OBYA4G525xAUoWXm00CAwXLCdPn9tr1Fdj+1l7jypnbIq0wXcdlUJWcq+ec+ZJIxIQbVP2PY80eVCLuP9dw3llmyxotjlbHhnKipEFfJlifLCZErJMLsn7NBx8rol0dmcl8jczMvS4favxoxhzwXbeAydXtkQDQcygpHGMzYJ7lOWQ6igGLHxNNhYGMtVndC5/xv44to1rrXMp6pZVBbrtoL3TO9i5HZcqehNBNSNDB6103Siw0ZviR1BG6GOBDV7MZ2Lps0MthSEIq8pVGGQ2Z83RgBjZ7zjsovMgRPUc8d3+Kkb01q28GrBwPQvQ4/1IINe2BTgxGEY+jFCihUnwjA9w==
  template:
    metadata:
      creationTimestamp: null
      name: router-apikey
      namespace: data-gateway

