apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graph-monitoring
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ default .Release.Namespace .Values.project }}
  source:
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision }}
    path: {{ .Values.source.monitoring.path }}
  destination:
    name: {{ .Values.destination.name }}
    server: {{ .Values.destination.server }}
    namespace: {{ default .Release.Namespace .Values.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
