apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graph-nightly
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ default .Release.Namespace .Values.project }}
  sources:
    - repoURL: {{ .Values.graph.repoURL }}
      targetRevision: {{ .Values.graph.nightlyRevision }}
      path: {{ .Values.graph.path }}
      helm:
        valuesObject:
          router:
            router:
              configuration:
                telemetry:
                  exporters:
                    metrics:
                      common:
                        resource:
                          "service.name": "router-nightly"
                      otlp:
                        enabled: true
                        endpoint: 'graph-monitoring-opentelemetry-collector:4317'
                        protocol: grpc
                    tracing:
                      common:
                        resource:
                          "service.name": "router-nightly"
                      otlp:
                        enabled: true
                        endpoint: 'graph-monitoring-opentelemetry-collector:4317'
                        protocol: grpc
                      propagation:
                        trace_context: true
          oauth2-proxy:
            ingress:
              hostname: graph-nightly.diamond.ac.uk
              hosts:
                - graph-nightly.diamond.ac.uk
            alphaConfig:
              configData:
                providers:
                  - provider: oidc
                    scope: "openid profile email fedid"
                    clientId: graph-nightly
                    clientSecretFile: /etc/alpha/client-secret
                    id: authn
                    oidcConfig:
                      issuerURL: https://authn.diamond.ac.uk/realms/dls
                      insecureAllowUnverifiedEmail: true
                      audienceClaims:
                        - aud
                      emailClaim: email
                      userIDClaim: email
    - repoURL: {{ .Values.schema.repoURL }}
      chart: {{ .Values.schema.chart }}
      targetRevision: {{ .Values.schema.nightlyRevision | quote }}
  destination:
    name: {{ .Values.destination.name }}
    server: {{ .Values.destination.server }}
    namespace: {{ default .Release.Namespace .Values.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
