apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graph-stable
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ default .Release.Namespace .Values.project }}
  sources:
    - repoURL: {{ .Values.graph.repoURL }}
      targetRevision: {{ .Values.graph.targetRevision }}
      path: {{ .Values.graph.path }}
      helm:
        valuesObject:
          router:
            router:
              configuration:
                telemetry:
                  exporters:
                    metrics:
                      common:
                        resource:
                          "service.name": "router-stable"
                      otlp:
                        enabled: true
                        endpoint: 'graph-monitoring-opentelemetry-collector:4317'
                        protocol: grpc
                    tracing:
                      common:
                        resource:
                          "service.name": "router-stable"
                      otlp:
                        enabled: true
                        endpoint: 'graph-monitoring-opentelemetry-collector:4317'
                        protocol: grpc
                      propagation:
                        trace_context: true
    - repoURL: {{ .Values.schema.repoURL }}
      chart: {{ .Values.schema.chart }}
      targetRevision: {{ .Values.schema.targetRevision }}
  destination:
    name: {{ .Values.destination.name }}
    server: {{ .Values.destination.server }}
    namespace: {{ default .Release.Namespace .Values.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
