apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: "{{ .Release.Name }}-oauth2-client"
  namespace: graph
spec:
  template:
    type: Opaque
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: "{{ .Release.Name }}-oauth2-client"
      namespace: graph
  encryptedData:
    secret: AgBm/HFZ+1zmTRLltG4bUk4/SCKb5YFlAswVrPChZzUF395p/wgkhpniLMoJAIpcpYNL6antxz/168S185TrVuu2NOZGXaf+4VH8Cn6JzDjaj3P86D9pYKyLePIWoAnIYP1bsyeh6RVg30yluXIGN/4dlhZPnpP5idr3iITYwnk04NwWsdLT9SItit+jxS7Uu7cfF77+WMbvYT5OKcMf1vNqHNcZXfL7gHG0NNPqBfiFqcbcf71I9zPxEK6JiRLIYHQNMVasYd4ml1ZayQxjjNOjOg262DFGcFKLC7NIPWOlpIhtMEQfCl7nH28pufdcIFTDrxvxpyj9EGJRqKnsgeIsI2H68UXXWCcjGcLZX09Hd80ejMwj093/TAnYngaLFIQclpym3Um8XKiLj0/4W+KkHj4CVjnJEou3ikbF3Kn7XewAE8xzyHrbPJEn6cWBC45tpZsO9B3Iy65LKB3RJC/qI6k9FUnZ1EwY/AZU65S1TzE2gzzAeMuXD8OlWyxxH+lsFWrLu1xfm2FtzQc4Zlbk214OHUIE1LSQ6odp/Pbd4T1OeizZU5ot7XvCylBbMECQ7JRT+prFwQIexpwbZ31VREYoFr/j8v5OngD1sT/pk6jCp9TqAGVl59QkPZpiXW31KPn4ojXOr+tvabVkod/pe21zgdtvj0dRyS9MIFexia0HIMPq0tnQPaE5yJY2UHezZA/1fVToC3PQytG0Zqj/JrfZyzhgOMAqDPMmUvF8bA==
