name: Compose Workflow

on:
  workflow_call:

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Create Test Subgraph schema
        run: >
          echo "
            schema {
              query: Query
            }
            type Query {
              _empty: String
            }
          " > test-schema.graphql

      - name: Upload Test Subgraph schema
        uses: actions/upload-artifact@v4.4.3
        with:
          name: test-compose-schema
          path: test-schema.graphql

      - name: Compose Supergraph
        uses: ./workflows/compose
        with:
          name: test
          routing-url: https://example.com/graphql
          subgraph-schema-artifact: test-compose-schema
          subgraph-schema-filename: test-schema.graphql
          supergraph-schema-artifact: compose-supergraph
