name: Helm Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0

      - name: Setup chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Install chart dependencies
        run: |
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
          helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo add oauth2-proxy https://oauth2-proxy.github.io/manifests

      - name: Lint
        run: >
          ct
          lint
          --target-branch=${{ github.event.repository.default_branch }}
          --validate-maintainers=false
          --check-version-increment=false
