name: Release Please

on:
  workflow_call:

jobs:
  release_please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Prerelease Please
        id: prerelease
        uses: googleapis/release-please-action@v4.1.3
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          skip-github-release: true
          skip-github-pull-request: true

      - name: Release Please Outputs
        run: echo "${{ toJson(steps.release.outputs) }}"
