name: Publish Supergraph Schema

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        required: true
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0

      - name: Download Schema Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: supergraph.graphql
          path: charts/supergraph

      - name: Package Chart
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          helm package charts/supergraph --version $LATEST_TAG

      - name: Generate Image Name
        run: echo IMAGE_REPOSITORY=oci://ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]' | tr '[_]' '[\-]') >> $GITHUB_ENV

      - name: Log in to GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Chart
        if: ${{ inputs.publish }}
        run: helm push $(ls supergraph-*.tgz) ${{ env.IMAGE_REPOSITORY }}
