name: Generate Supergraph Schema

on:
  workflow_call:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rover CLI
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Checkout Source
        uses: actions/checkout@v4.2.2

      - name: Compose Supergraph Schema
        run: >
          rover supergraph compose
          --config supergraph-config.yaml
          --elv2-license=accept
          > supergraph.graphql

      - name: Upload New Schema Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: supergraph.graphql
          path: supergraph.graphql

