name: Publish Supergraph Schema

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0

      - name: Download Schema Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: supergraph.graphql
          path: charts/supergraph

      - name: Generate Chart Version
        id: version
        run: |
          if LATEST_TAG=$(git describe --tags --abbrev=0 --match supergraph@*); then
            LATEST_VERSION=$(cut --delimiter '@' --fields 2 "$LATEST_TAG" | cut --characters 2-)
            COMMITS_SINCE=$(git rev-list $LATEST_TAG..HEAD --count)
          else
            LATEST_VERSION="0.0.0"
            COMMITS_SINCE=$(git rev-list HEAD --count)
          fi
          if [ "$COMMITS_SINCE" == 0 ]; then
            VERSION="$LATEST_VERSION"
          else
            VERSION="$LATEST_VERSION-pre.$COMMITS_SINCE"
          echo "Using Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Package Chart
        run: helm package charts/supergraph --version "${{ steps.version.outputs.version }}"

      - name: Generate Image Name
        run: |
          IMAGE_REPOSITORY="oci://ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]' | tr '[_]' '[\-]')"
          echo "Using Image Name: $IMAGE_REPOSITORY"
          echo "IMAGE_REPOSITORY=$IMAGE_REPOSITORY" >> $GITHUB_ENV

      - name: Log in to GitHub Docker Registry
        if: github.event_name == 'push' && ( startsWith(github.ref, 'refs/tags') || startsWith(github.ref, 'refs/heads/main') )
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Chart
        if: github.event_name == 'push' && ( startsWith(github.ref, 'refs/tags') || startsWith(github.ref, 'refs/heads/main') )
        run: helm push $(ls supergraph-*.tgz) ${{ env.IMAGE_REPOSITORY }}
