name: Publish Supergraph Schema

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4.1.0

      - name: Install release-please
        run: npm install release-please

      - name: Generate Chart Version
        id: version
        uses: actions/github-script@v7.0.1
        with:
          result-encoding: string
          script: |
            const releasePlease = require('release-please');

            const ghRelease = await releasePlease.GitHub.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              token: '${{ github.token }}'
            });

            const manifest = await releasePlease.Manifest.fromManifest(
              ghRelease,
              ghRelease.repository.defaultBranch,
              'release-please-config.json',
              '.release-please-manifest.json',
              {}
            );

            const pullRequests = await manifest.buildPullRequests();
            const pullRequest = pullRequests.find((pullRequest) => pullRequest.updates.some((update) => update.path === 'charts/supergraph'));
            return pullRequest ? pullRequest.version : ''

      - name: Setup Helm
        if: steps.version.output != ''
        uses: azure/setup-helm@v4.2.0

      - name: Download Schema Artifact
        if: steps.version.output != ''
        uses: actions/download-artifact@v4.1.8
        with:
          name: supergraph.graphql
          path: charts/supergraph

      - name: Package Chart
        if: steps.version.output != ''
        run: helm package charts/supergraph --version "${{ steps.version.outputs.result }}"

      - name: Generate Image Name
        if: steps.version.output != ''
        run: |
          IMAGE_REPOSITORY="oci://ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]' | tr '[_]' '[\-]')"
          echo "Using Image Name: $IMAGE_REPOSITORY"
          echo "IMAGE_REPOSITORY=$IMAGE_REPOSITORY" >> $GITHUB_ENV

      - name: Log in to GitHub Docker Registry
        if: steps.version.output != '' && github.event_name == 'push' && ( startsWith(github.ref, 'refs/tags') || startsWith(github.ref, 'refs/heads/main') )
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Chart
        if: steps.version.output != '' && github.event_name == 'push' && ( startsWith(github.ref, 'refs/tags') || startsWith(github.ref, 'refs/heads/main') )
        run: helm push $(ls supergraph-*.tgz) ${{ env.IMAGE_REPOSITORY }}
