name: Update Workflow

on:
  workflow_call:
    secrets:
      GRAPH_FEDERATOR:
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.1

      - name: Create Test Subgraph schema
        run: >
          echo "
            schema {
              query: Query
            }
            type Query {
              _empty: String
            }
          " > test-schema.graphql

      - name: Upload Test Subgraph schema
        uses: actions/upload-artifact@v4.4.3
        with:
          name: test-update-schema
          path: test-schema.graphql

      - name: Update Supergraph
        uses: ./workflows/update
        with:
          name: test
          routing-url: https://example.com/graphql
          subgraph-schema-artifact: test-update-schema
          subgraph-schema-filename: test-schema.graphql
          supergraph-schema-artifact: update-supergraph
          github-app-id: 1115262
          github-app-private-key: ${{ secrets.GRAPH_FEDERATOR }}
          publish: false
