name: Helm Charts

on:
  push:
  pull_request:

jobs:
  lint:
    # Deduplicate jobs from pull requests and branch pushes within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v3.5

      - name: Setup chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Install chart dependencies
        run: |
          helm repo add prometheus https://prometheus-community.github.io/helm-charts

      - name: Lint
        run: >
          ct
          lint
          --target-branch=${{ github.event.repository.default_branch }}
          --validate-maintainers=false
