name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      apps-chart-released: ${{ contains(steps.release.outputs.paths_released, 'charts/apps') }}
      graph-chart-released: ${{ contains(steps.release.outputs.paths_released, 'charts/graph') }}
      monitoring-chart-released: ${{ contains(steps.release.outputs.paths_released, 'charts/monitoring') }}
      supergraph-chart-released: ${{ contains(steps.release.outputs.paths_released, 'charts/supergraph') }}
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Release Please Outputs
        run: echo "${{ toJson(steps.release.outputs) }}"
